require 'prawn'
require 'prawn/table'

class PdfGenerator
  def initialize(contract, analysis)
    @contract = contract
    @analysis = analysis
    @critical = analysis["critical_risks"] || []
    @moderate = analysis["moderate_risks"] || []
    @low = analysis["low_risks"] || []
    @summary = analysis["summary"] || "No summary available."
    @risk_score = calculate_risk_score
  end

  def generate
    Prawn::Document.new do
      # Header
      text "Smart Contract Analysis Report", size: 24, style: :bold, align: :center
      move_down 20
      
      # Contract Information
      text "Contract Information", size: 18, style: :bold
      move_down 10
      
      data = [
        ["Contract ID:", @contract.id.to_s],
        ["File Name:", @contract.file.attached? ? @contract.file.filename.to_s : "N/A"],
        ["Question:", @contract.question || "N/A"],
        ["Analyzed At:", @contract.updated_at.strftime("%B %d, %Y at %I:%M %p")]
      ]
      
      table(data, width: 500) do
        cells.border_width = 0
        columns(0).font_style = :bold
        columns(0).width = 150
      end
      
      move_down 30
      
      # Risk Score
      text "Overall Risk Score", size: 18, style: :bold
      move_down 10
      text "#{@risk_score}%", size: 48, style: :bold, align: :center
      move_down 5
      
      risk_level = case @risk_score
      when 0..50 then "CRITICAL RISK"
      when 51..80 then "MODERATE RISK"
      else "LOW RISK"
      end
      
      text risk_level, size: 14, align: :center, style: :bold
      move_down 30
      
      # Risk Breakdown
      text "Risk Breakdown", size: 18, style: :bold
      move_down 15
      
      # Critical Risks
      if @critical.any?
        text "Critical Risks (#{@critical.size})", size: 14, style: :bold, color: "000000"
        move_down 5
        @critical.each_with_index do |risk, index|
          text "#{index + 1}. #{risk}", size: 11
          move_down 3
        end
        move_down 15
      end
      
      # Moderate Risks
      if @moderate.any?
        text "Moderate Risks (#{@moderate.size})", size: 14, style: :bold, color: "333333"
        move_down 5
        @moderate.each_with_index do |risk, index|
          text "#{index + 1}. #{risk}", size: 11
          move_down 3
        end
        move_down 15
      end
      
      # Low Risks
      if @low.any?
        text "Low Risks (#{@low.size})", size: 14, style: :bold, color: "666666"
        move_down 5
        @low.each_with_index do |risk, index|
          text "#{index + 1}. #{risk}", size: 11
          move_down 3
        end
        move_down 15
      end
      
      if @critical.empty? && @moderate.empty? && @low.empty?
        text "No specific risks identified.", size: 11, style: :italic
        move_down 15
      end
      
      # Summary
      move_down 10
      text "Summary", size: 18, style: :bold
      move_down 10
      text @summary, size: 11, align: :justify
      
      # Footer
      move_down 30
      text "Generated by Smart Contract Analyzer", size: 8, align: :center, style: :italic, color: "999999"
    end.render
  end

  private

  def calculate_risk_score
    score = 100 - (@critical.size * 20 + @moderate.size * 10 + @low.size * 3)
    score.clamp(0, 100)
  end
end
